[package]
name = "activitypub-rust-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.8.0", features = ["openssl", "rustls-0_23"] }
openssl = "0.10.64"
rustls = "0.23.11"
rustls-pemfile = "2.1.2"
serde = "1.0.204"
serde_json = "1.0.120"
